## PostgreSQL. Versions 8.2 and up are supported.
#
default: &default
  encoding: unicode
  template: template0
  adapter: postgresql
  username: docker
  pool: 5

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling


development:
  <<: *default
  host: localhost
  database: leangreen
  password: docker

production:
  <<: *default
  host: db
  database: docker
  # host: localhost
  password: <%= ENV['DATABASE_PASSWORD'] %>
    # <%= ENV['DATABASE_PASSWORD'] %>
  # password: docker
