## PostgreSQL. Versions 8.2 and up are supported.
#
default: &default
  encoding: unicode
  template: template0
  adapter: postgresql
  pool: 5

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling


development:
  <<: *default
  host: localhost
  database: leangreen

production:
  <<: *default
  # username: docker
  # host: db
  # database: docker
  host: localhost
  database: leangreen
  # password: docker
    # <%= ENV['DATABASE_PASSWORD'] %>
  # password: docker
